### ISSUE TITLE
Can't parse floats?

### ISSUE THREAD

**Issue by hookenz** [sirkon/ldetool#25]
Great project.  But I so wish the documentation was better explained with more examples.

For example, I'm having great trouble with this

e.g. 
   17.965 Pump 10 hose FF price level 1 limit    0.0000 authorise pending (Type 00)

I tried this but it doesn't work when limit is a float32.
```
Auth =
    Offset(string)
    " Pump " Pump(int8)
    " hose " Hose(hex8)
    " price level " PriceLevel(int8)
    " limit " Limit(string);
    " authorise pending ";
```
It works as a string, but not float32

What am I doing wrong?

**Comment by sirkon** [comment]
Thank you for the report.

The issue is you put `;` after `Limit(string)` and the tool not saying about syntax error which remained `" authorize pending ";` should be.

Will try to fix syntax error reporting as soon as possible, at the weekend most probably. Don't forget to remove `;` after `Limit(string)` :)

**Comment by sirkon** [comment]
Fixed as it was just a tiny fix in the grammar. Checkout the latest version (v0.0.5):

```
$ ldetool generate --package main auth.lde
auth.lde:7:4: extraneous input '" authorise pending "' expecting {<EOF>, Identifier}
```

**Comment by hookenz** [comment]
Thanks Denis,   This is really a great tool.  Starting to get used to the grammar.
